### ISSUE TITLE
Feature Request: Automatically run `xattr -r -d com.apple.quarantine "#{target_dir}"` after the installation

### ISSUE THREAD

**Issue by murphye** [graalvm/homebrew-tap#44]
Trying to install CE 22.2 onto my MacBook Air M1. Install seems to go OK but I cannot run the executable. See the screenshot.

Zip of the `bin` folder attached.

<img width="1335" alt="Screen Shot 2022-07-30 at 10 10 32 AM" src="https://user-images.githubusercontent.com/643097/181934375-600583dd-e467-49fd-bbc9-338e93eea719.png">

[bin.zip](https://github.com/graalvm/homebrew-tap/files/9226976/bin.zip)

Currently using macOS 12.4

**Comment by murphye** [comment]
java11 binary also has the same problem

**Comment by FranklinChen** [comment]
Run

```
xattr -r -d com.apple.quarantine "/Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0
```

**Comment by murphye** [comment]
OK. Looks like that fixed it! 

I would recommend changing this instruction to also encompass the "damaged and can't be opened" error:

```
On macOS Catalina, you may get a warning that "the developer cannot be
verified". This check can be disabled in the "Security & Privacy"
preferences pane or by running the following command:
  xattr -r -d com.apple.quarantine "/Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0"
```

**Comment by murphye** [comment]
Also, is it possible for Homebrew to run `xattr -r -d com.apple.quarantine "/Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0` automatically?

**Comment by murphye** [comment]
Change this issue into a Feature Request to automatically run `xattr -r -d com.apple.quarantine "/Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0"`.

**Comment by fniephaus** [comment]
We have discussed this problem before (e.g., in #6 and #28). GraalVM bundles are unfortunately not notarized by Apple and thus, users are require to remove the quarantine attribute before use. While it would make for a better user experience, the GraalVM casks do not automatically do this because we'd work around a security measurement for the user which is bad. Instead, the casks mention what to do in the post installation message. That's the best we can do at this point. The correct fix is to get the bundles notarized and we are working on that.
